### ISSUE TITLE
wgo-exec prepend W/vendor/bin to PATH

### ISSUE THREAD

**Issue by mmindenhall** [skelterjohn/wgo#10]
After months of using wgo, I just discovered today that commands I've been executing via wgo-exec have worked only because the command had been installed via both `wgo get` and `go get`, and it was the version in `$GOPATH/bin` that was being executed instead of the vendored version in `W/vendor/bin`.

Would it be possible for wgo-exec to to prepend `W/vendor/bin` to the path prior to executing the go command?

**Comment by skelterjohn** [comment]
That's an interesting idea, but I'm not so sure it makes sense. wgo-exec is
a tool to set GOPATH for a command, mainly other developer tools that use
GOPATH. Are the things you're running using GOPATH?

**Comment by mmindenhall** [comment]
> wgo-exec is a tool to set GOPATH for a command, mainly other developer tools that use GOPATH. 

I would say that wgo-exec is a tool to run a command within the context of a particular workspace W.   For all the same reasons it makes sense to vendor library dependencies, it also makes sense to vendor command dependencies.  In some cases, a vendored library is intended to be used with one or more commands that are released in lockstep, and tested for mutual compatibility.  

> Are the things you're running using GOPATH?

Yes.  Specifically, we're using beego (github.com/astaxie/beego) and bee (github.com/beego/bee).  You're probably familiar with beego as a web framework.  Bee is a developer tool that makes working with beego easier (most importantly, runs the project to detect code changes and automatically rebuild/restart).  Bee absolutely depends on the GOPATH set by wgo-exec, as it shells out to `go build` when starting or restarting.  Previously I was running like this (from W/src/mypackage), which was actually executing GOPATH/bin/bee instead of W/vendor/bin/bee:

```
$ wgo-exec bee run
```

I have two projects using beego/bee for web apps and/or REST APIs.  One of them was recently updated to the latest beego/bee versions, while the other is a version behind.  I want to keep them both using the vendored version of bee that was released in lockstep with the vendored version of beego.  Now I need to run like this instead (from W/src/mypackage):

```
$ PATH=../../vendor/bin:$PATH wgo-exec bee run
```

The last point I'll make is that I see little harm from doing this.  If someone has vendored the command, the vendored version at W/vendor/bin will be executed (as expected, IMHO).  If the command is not vendored, it will be found at GOPATH/bin and executed from there.

**Comment by skelterjohn** [comment]
Done with https://github.com/skelterjohn/wgo/commit/845c86be7113cca99db5b7f7708bdd388bf9b2da

**Comment by mmindenhall** [comment]
Works great!  Thanks for quick response!
