### ISSUE TITLE
There are no installation instructions

### ISSUE THREAD

**Issue by brandon-fryslie** [skelterjohn/wgo#15]
How do I install `wgo`?  There are no installation instructions in the README.md, and the name of the tool suffers from un-googleability so it is not easy to find them on any other website either.  It would be useful to have installation instructions in the README so new users can figure out how to install and use the tool.

**Comment by skelterjohn** [comment]
You can use `go get github.com/skelterjohn/wgo`. It has no dependencies outside the stdlib, my repos, and some golang.org/x/* packages, so there shouldn't be any version conflicts.

**Comment by brandon-fryslie** [comment]
Thanks for the quick response, but it would be nice if this was directly in the README.md.  It is certainly not obvious that this is how to install it unless you are already familiar with golang in general.
