### ISSUE TITLE
Using wgo get on a newly initialized project does not download package

### ISSUE THREAD

**Issue by jbuberel** [skelterjohn/wgo#3]
Giving `wgo` a quick test on Win8.1, tried to use the `wgo get` command to install the go-sql-driver/mysql package, but nothing was downloaded:

```
jason_000@velocity-micro /c/Users/jason_000
$ cd wgotest/

jason_000@velocity-micro /c/Users/jason_000/wgotest
$ wgo init

jason_000@velocity-micro /c/Users/jason_000/wgotest
$ wgo get github.com/go-sql-driver/mysql

jason_000@velocity-micro /c/Users/jason_000/wgotest
$ ls
src
```

The contents of the generated gopaths file are:

```
third_party
.
```

So I expected that the mysql driver would have been installed into:

```
wgotest/third_party/github.com/go-sql-driver/mysql
```

What did I do wrong?

**Comment by skelterjohn** [comment]
You must already have that package in your GOPATH somewhere. wgo augments the GOPATH already in your environment with the directories from your workspace. So, if that package is already there, 'go get' says "ok got it!" and succeeds without action.

If you 'wgo import' it will copy it into third_party.
