### ISSUE TITLE
wgo install installs binary in wrong path

### ISSUE THREAD

**Issue by bdandy** [skelterjohn/wgo#4]
If I have environment variable `GOBIN` set - `wgo install` installs binary to `GOBIN` instead of current `GOPATH/bin` directory

**Comment by skelterjohn** [comment]
Then that can only be because that is how the go tool works. Should wgo differ, here? I think probably not.

**Comment by skelterjohn** [comment]
According to https://golang.org/cmd/go/#hdr-GOPATH_environment_variable this is the desired behavior. So, I'm going to mark this as a wont-fix.

**Comment by bdandy** [comment]
I guess you'd like to create tool that makes independent workspaces. Thats why you change GOROOT. Why not change GOBIN? It doesn't allow to use your tool properly. Dislike

**Comment by skelterjohn** [comment]
wgo doesn't change GOROOT. And, setting GOBIN is not typical. Most people
don't set GOBIN, which results in their binaries being put in $GOPATH/bin.

If you leave it unset, then your binaries will be put in W/bin.

**Comment by bdandy** [comment]
I haven't set GOBIN path, it's my system defaults - `GOBIN=$GOPATH/bin`

**Comment by skelterjohn** [comment]
It _definitely_ should not be in your system defaults. Beyond that, GOPATH
is a directly list (though it might be a single directory in your case), so
setting GOBIN=$GOPATH/bin is incorrect.

Take that out of your system defaults, and no behavior will change except
that wgo will put things where you want it to.
