### ISSUE TITLE
Allow to run any command

### ISSUE THREAD

**Issue by bdandy** [skelterjohn/wgo#5]
I'd like to run any command with `wgo`, for example `goimports`, `gom`, etc.

**Comment by skelterjohn** [comment]
I'd prefer not to give wgo special knowledge of many non-the-go-tool commands.

However, you can do "$ export GOPATH=$(wgo env GOPATH)".

Anything other than setting an environment variable like that would require some kind of 'wgo exec goimports' incantation, which strikes me as less convenient than setting the env var as shown.

**Comment by AmandaCameron** [comment]
TBH this kind of stuff is  why I'd like there to be `go tool <foo>` would shell out to go-tool-foo or similar, in the vanilla Go tool. But I guess that's just wishful thinking at this point. :P
