### ISSUE TITLE
`wgo build` doesn't rebuild updated dependencies

### ISSUE THREAD

**Issue by deweerdt** [skelterjohn/wgo#8]
After a `wgo restore`, if that resulted in one of the dependecies being updated, issuing a `wgo build` won't rebuild said dependency. Our workaround is to remove vendor/pkg to make sure the rebuild happens. Is this intentional, are we doing something wrong or is this a real issue?

Thanks,
Frederik

**Comment by skelterjohn** [comment]
Since 'wgo build' only forwards it to the go tool, that means the source
didn't actually change.

**Comment by deweerdt** [comment]
I see, thanks. What I see is that even removing .go files from under vendor/src doesn't trigger a build failure. I've tried setting up simple repos but I can't reproduce that with simple cases.

I'm suspecting the issue might have to do with the fact that the vendored dependency is compiled as a .a under `vendor/pkg`. Do you know what triggers the fact that a lib is being built as a separate object rather than statically compiled as a binary?

**Comment by skelterjohn** [comment]
http://gowithconfidence.tumblr.com/post/118493925546/getting-started-with-go-workspaces

On Thu, Oct 29, 2015 at 1:29 PM, Frederik Deweerdt <notifications@github.com

**Comment by deweerdt** [comment]
Thanks, it turns out I can only repro when building in docker (using golang as a base image). I've also verified that `wgo restore` does pull the right sources. If I manually set GOPATH to <prj>:vendor/<prj> and directly invoke `go install`, I still see the issue (the `.a` is not rebuilt). If anything this is a `go` tool issue.

Thanks for the help.
