### ISSUE TITLE
Unable to install wgo with Go 1.6 beta

### ISSUE THREAD

**Issue by lming** [skelterjohn/wgo#9]
$ go version
go version go1.6beta1 linux/amd64

$ go get github.com/skelterjohn/wgo
package github.com/skelterjohn/wgo
    imports github.com/skelterjohn/vendor/vend: must be imported as vend

**Comment by skelterjohn** [comment]
ugh... thanks

**Comment by skelterjohn** [comment]
Moved the vendor repo to github.com/skelterjohn/vfu.

**Comment by lming** [comment]
Thanks for the quick fix!
